### ISSUE TITLE
Update https://mikewest.github.io/cors-rfc1918/ link in repo description

### ISSUE THREAD

**Issue by foolip** [WICG/cors-rfc1918#12]
It redirects to https://wicg.github.io/cors-rfc1918/

(Noticing because I wrote a script to iterate all WICG repos and try to follow such links, checking which don't appear in https://foolip.github.io/day-to-day/)

**Comment by letitz** [comment]
I think this is done. When I visit https://github.com/WICG/cors-rfc1918/, I see the wicg.github.io link on the right.
