### ISSUE TITLE
Should we explicitly define cors-rfc1918 behavior for opaque origins?

### ISSUE THREAD

**Issue by anforowicz** [WICG/cors-rfc1918#17]
This came up in https://chromium-review.googlesource.com/c/chromium/src/+/1713563, when discussing whether it is possible to map an arbitrary origin to an ip-address-space (loopback / local / private).  What should be the behavior for opaque origins?

Some examples of more specific questions:
- Should a sandboxed frame be treated as an unprivileged (e.g. public) ip-address-space?  Or should it inherit the ip-address-space flag from the origin's precursor (e.g. if the frame's content comes from or is controlled by https://intranet.example.com then maybe ip-address-space should be "local")?
- What should be the ip-address-space of data: URLs (e.g. ones created by loopback and/or local frames)?

**Comment by letitz** [comment]
Yes, we should! There is no good reason to leave this unspecified.

> Should a sandboxed frame be treated as an unprivileged (e.g. public) ip-address-space? Or should it inherit the ip-address-space flag from the origin's precursor (e.g. if the frame's content comes from or is controlled by https://intranet.example.com then maybe ip-address-space should be "local")?

I think it should inherit the address space of the origin's precursor. Not sure what security benefits would come from treating it as public unconditionally.

> What should be the ip-address-space of data: URLs (e.g. ones created by loopback and/or local frames)?

I believe such URLs should inherit the address space of their creator. Same here, I'm not sure what we would gain from treating those as public.

**Comment by anforowicz** [comment]
> Not sure what security benefits would come from treating it as public unconditionally.

The `sandbox` attribute is used when the embedding frame doesn't fully trust the subframe and therefore wants to limit capabilities of the subframe.  For example, maybe the subframe executes third-party javascript - in this case the embedding frame might want to avoid granting the subframe the ability to issue `Sec-Fetch-Site: same-origin` and/or SameSite cookie requests.  Similarily, we might want to avoid granting the subframe the ability to use the ambient authority of being on the intranet (VS public IP address).

**Comment by letitz** [comment]
Thanks for explaining! Just to make sure, the scenario would be: site A (served from e.g. private IP) wants to execute a script from site B, so it embeds a sandboxed iframe which loads its contents from site A and a script from site B, then executes the script in that context?

In that case, it seems reasonable to default the iframe to `public` and forbid it from using site A's ambient authority indeed.

I'm not sure the same applies to documents loaded from `data:` URLs. Do you have an opinion on those?

**Comment by anforowicz** [comment]
I don't have a strong opinion on `data:` URLs, but I would lean toward also treating them as `public`.

I understand that the trustworthiness decision is less explicit for `data:` URLs than it is for sandboxing.  In some scenarios the embedder of a `data:` URL may trust the contents of the URL.  In other scenarios the contents of the `data:` URL may come from an untrustworthy source (e.g. think about embedding user-provided html content).

Still, for better of for worse it has been decided that `data:` URLs should use opaque origins - I think that we should treat them consistently with other opaque origins (e.g. with sandboxed frames).  This argues to default treating opaque origins as `public` (from the private-vs-public-network perspective).

**Comment by annevk** [comment]
I'm not sure it makes sense to base the decision on whether the document has an opaque origin, as a document with a private IP address can also have an opaque origin (e.g., through a CSP header).

**Comment by letitz** [comment]
It is indeed unclear whether opaque origins should all behave the same way wrt IP address spaces.

It might make sense to introduce another dimension to sandboxing: IP address / `allow-ip`?

Then inheritance of this attribute could be controlled by an iframe's `sandbox` attribute, and we could maybe replace `treat-as-public-address` with CSP's `sandbox` directive? I guess `sandbox` is an allowlist and so would require listing all non-sandboxed capabilities, which might make it harder to maintain as other dimensions are added over time.

In any case, I believe @mikewest has opinions on this matter. He's on vacation this week though, so we'll have to wait a bit :)

**Comment by letitz** [comment]
Given this some more thought with some input from @mikewest. Here's what I think:

1. `data:` URL iframes should inherit the address space of their parent
   - The URL was set by the parent frame
   - We only care about defending the private network from public websites

2. I think sandboxed iframes should be `public` by default. We should add a `sandbox` attribute to allow inheritance of address space / private network access. This allows web developers to construct secure intranet websites while including some untrusted content from the public web. All that said, it is significantly lower priority than securing intranet websites from *all* public websties. Filed a new issue for this #26.

**Comment by annevk** [comment]
The conclusion for data URLs does not seem sound and is in fact why we moved away from inheriting the origin for data URLs. Namely, a frame can be navigated to a data URL by any party that can target the frame.

**Comment by annevk** [comment]
Also, unless that was specified somehow it seems this should be reopened until it's defined?

**Comment by letitz** [comment]
Thanks Anne for the background, I was not aware of the reasoning there (and probably should have asked for clarification...). If the provenance of the URL cannot be trusted, then `public` it is!

I did close this issue a tad early, but rest assured I opened an issue to fix the specification: #27.

**Comment by annevk** [comment]
Thanks for following up quickly!

**Comment by letitz** [comment]
My thinking on this has evolved: I think we should inherit the address space of the *navigation initiator* for `data:` URLs. This is usually the parent in simple cases, but also solves the problem raised in https://github.com/WICG/cors-rfc1918/issues/17#issuecomment-724715970. See https://github.com/WICG/cors-rfc1918/issues/27 for an overview of inheritance rules.
