### ISSUE TITLE
Granting public to private fetching shouldn't grant cross-origin access

### ISSUE THREAD

**Issue by jschuh** [WICG/cors-rfc1918#2]
Simply put, we should provide an easy way for an origin to opt into the old behavior without also granting cross-origin permissions. Consider the common enterprise case of outsourcing email, calendar, or document sharing to a third-party service provider such as Google Apps, Dropbox, or Microsoft Office 365. These enterprises will still want links, framing, and other integration to work as it would on the public Web, but enabling those use cases shouldn't also allow arbitrary data access from these third-party origins.

Unfortunately, none of the existing CORS Access-Control-Allow-\* headers express the right semantics. My strawman proposal is to add new headers of the form:

```
Access-Control-Allow-Public: <origin> | *
```

The behavior would be to allow public -> private, private -> local, and public -> local with normal origin restrictions on a match. That would provide for good defense-in-depth for collaborating origins tightly integrated with the private service. It also means you can enable the legacy private address behavior by just sending the following header:

```
Access-Control-Allow-Public: *
```

**Comment by annevk** [comment]
I think this is the same concern I outlined in https://github.com/w3c/webappsec-subresource-integrity/issues/21#issuecomment-331383633.

CORS is about sharing content and the moment you start using it for something else, you are tightly coupling things that should not be coupled.

It sounds like this might be mostly addressed now, though @mikewest calling it CORS++ makes me worried.

**Comment by letitz** [comment]
Sounds like this issue is resolved by https://github.com/WICG/cors-rfc1918/commit/21e5b45869f2fa7ca5082950fe6069a148f23125?

**Comment by letitz** [comment]
I think it is. Please re-open if you disagree.
