### ISSUE TITLE
Link-local IP addresses should be considered private

### ISSUE THREAD

**Issue by letitz** [WICG/cors-rfc1918#29]
Right now the spec classifies them as `local`, but they are closer in behavior to IPv4's RFC1918 private address space than `localhost`.

Point raised in #28 .

cc @thejh

**Comment by thejh** [comment]
And the same thing applies for autoconfigured link-local IPv4 addresses.

**Comment by letitz** [comment]
That's right, renaming the issue.

**Comment by letitz** [comment]
This issue is superseded by #30 - solving that one solves this one.
